---

- name: Restart offlineimap service
  systemd:
    name: offlineimap@{{ item }}.service
    scope: user
    state: restarted
    daemon_reload: yes
  listen: reload offlineimap service
  when: offlineimap_manage_service
  loop: "{{ offlineimap_accounts | map(attribute='name') | list }}"
